site_name: Sparse Grids MATLAB Toolkit
theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand

use_directory_urls: false
nav:
  - Home: ../README.md
  - Examples:
    - Sparse Grids Tutorial: sparse_grids_tutorial.md
    - Adaptive Sparse Grids Tutorial: tutorial_adaptive.md
    - PlateauSC  Tutorial: tutorial_PlateauSC_adaptive.md
    - Spectral Sparse Grid Tutorial: test_spectral.md