name: Test and Coverage

on: [push]

jobs:
  my-job:
    name: Run MATLAB Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2

      - name: Run tests
        uses: matlab-actions/run-tests@v2  
        with:
          code-coverage-cobertura: test/coverage.xml
          test-results-junit: test/results.xml
          source-folder: src; tools; main; data
          select-by-folder: test

      - name: Upload MATLAB Test Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: matlab-test-results
          path: |
            test/results.xml

      - name: Upload MATLAB Coverage Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: matlab-coverage-results
          path: |
            test/coverage.xml
            
      - name: Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Tests            # Name of the check run which will be created
          path: test/results.xml    # Path to test results
          reporter: jest-junit        # Format of test results
  my-job2:
    name: Run MATLAB Coverage
    runs-on: ubuntu-latest

    steps:            
      - name: Parse Cobertura report and add to GitHub Action summary
        if: always()
        run: |
          # Install a coverage reporting tool (e.g., 'cobertura-coverage' GitHub Action)
          pip install pycobertura
          # Parse the Cobertura XML report and generate summary for GitHub Actions
          pycobertura show --format markdown --ignore-regex "data/*" test/coverage.xml > cobertura-summary.md
          # Add summary to GitHub Actions output
          echo "### Cobertura Coverage Summary" >> $GITHUB_STEP_SUMMARY
          cat cobertura-summary.md >> $GITHUB_STEP_SUMMARY
